export const SET_ORDER_IDS = 'SET_ORDER_IDS';
export const SET_DONE_ORDER_IDS = 'SET_DONE_ORDER_IDS';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const UPDATE_DAYS = 'UPDATE_DAYS';
export const MARK_ORDER_DONE = 'MARK_ORDER_DONE';
export const RESTORE_ORDER = 'RESTORE_ORDER';
